// ──────────────────────────────────────────────────────────────────────────
// fitFusion.ts — the calibrated bridge between the Fit Sim and reality.
//
// THE SIM↔DATA FUSION LOOP (the research contribution)
// ────────────────────────────────────────────────────
// Bra fit has a data problem: real fit outcomes are THIN and biased. People log
// a fitting only when something went wrong, and they record the LABEL they
// moved to — almost never the physics (gap/spill in mm) of why. You cannot
// train a fit model on that alone.
//
// So we run a loop in two directions:
//
//   1. PHYSICS BOOTSTRAPS WHERE DATA IS THIN.
//      lib/fitSim.ts turns body shape + cup geometry into a gap/spill/seat
//      verdict from first principles — no data required. scripts/fusion/
//      generate-synthetic.mjs runs it across a dense grid of (breast-twin ×
//      real bra geometry) to MANUFACTURE a fully-labelled synthetic dataset:
//      every cell knows its outcome, the kind of coverage real data can't give.
//
//   2. REAL OUTCOMES CORRECT THE PHYSICS.
//      The sim has free parameters — a forgiveness band (give0 / givePerStretch)
//      and how hard overflow scores (spillScale). scripts/fusion/calibrate.mjs
//      pins them to the one real signal we have: size-transitions.json, the
//      population's actual "I was labelled X, I really fit Y" moves (median:
//      down ~0.4 bands, up ~1.6 cups). It sweeps the params and keeps the set
//      whose label-size verdict best AGREES with those real moves.
//
// The output of (2) lives in data/froot/fusion-calibration.json. This module
// loads the recommended params so the sim and the ranking consume ONE source of
// truth, and exposes getFusionParams() for that.
//
// WHAT THIS LOOP CAN HONESTLY SHOW (current numbers, 142 real transitions):
//   • From geometry ALONE, the calibrated sim reproduces the population's
//     "size up a cup" tendency: ~84% verdict agreement with real moves, and a
//     ~0.86 correlation between predicted spill magnitude and the real cup-jump
//     size. The physics is directionally right and the data confirms it.
//   • Calibration lifted agreement ~+2pts over the raw fitSim defaults by
//     softening spill scoring — i.e. the data said the physics slightly
//     OVER-penalized overflow. A small, defensible correction, not a refit.
//
// WHAT IT CANNOT SHOW YET (be honest — this is a bet, not a finished result):
//   • No per-person ground-truth gap/spill in mm exists anywhere, so we
//     calibrate to band/cup AGREEMENT + directional correlation, never to a
//     measured millimetre error. The sim's mm outputs are internally
//     consistent, not externally validated.
//   • The sim systematically fails the "stayed the same size" cases (it calls
//     them spill/gap, never clean seat) — see calibration seatConfusion. It is
//     tuned to detect MISMATCH, not to certify a perfect fit.
//   • size-transitions are self-reported and survivorship-biased toward people
//     who refit; the per-size twin is a population mean. Individual shape
//     variance is swept synthetically, not observed.
//   • Community sentiment correlates only weakly (~0.28) with sim fit — a
//     sanity cross-check, not evidence.
//
// The honest frame: this is a physics prior, lightly corrected by the thin real
// data we have, built so that as MORE real outcomes arrive the same loop
// re-runs and the params tighten. The loop is the moat; the current fit is the
// first turn of it.
// ──────────────────────────────────────────────────────────────────────────

import calibration from '@/data/froot/fusion-calibration.json'

/** The three free parameters the Fit Sim exposes for calibration. */
export interface FusionParams {
  /** mm of forgiveness at zero stretch — the cup's base tolerance band. */
  give0: number
  /** extra mm of give at stretch = 1 — how much stretchy fabric forgives. */
  givePerStretch: number
  /** multiplier on spill magnitude before it scores as a defect. */
  spillScale: number
}

/** How well the recommended params line up with real outcomes. */
export interface FusionFit {
  /** weighted fraction of real size-transitions whose direction the sim agrees with (0..1). */
  agreement: number
  /** Pearson r between predicted spill mm and real cup-jump size. */
  spillJumpCorr: number
  /** composite objective: 0.7·agreement + 0.3·normalized(corr). */
  fit: number
  /** number of real size-transitions the calibration was scored against. */
  transitionsUsed: number
  /** secondary sanity check: corr of sim fit vs community brand sentiment. */
  communityCorr: number | null
}

// ── defaults: the raw fitSim.ts values, used if the calibration file is absent
const FALLBACK_PARAMS: FusionParams = { give0: 2, givePerStretch: 12, spillScale: 1 }

// Calibration JSON is generated by scripts/fusion/calibrate.mjs. Read defensively
// so a missing/partial file degrades to the physics defaults rather than throwing.
const REC = (calibration as { recommended?: { params?: Partial<FusionParams> } })?.recommended

/** The calibrated parameters the sim + ranking should consume. Frozen. */
export const FUSION_PARAMS: Readonly<FusionParams> = Object.freeze({
  give0: REC?.params?.give0 ?? FALLBACK_PARAMS.give0,
  givePerStretch: REC?.params?.givePerStretch ?? FALLBACK_PARAMS.givePerStretch,
  spillScale: REC?.params?.spillScale ?? FALLBACK_PARAMS.spillScale,
})

/**
 * getFusionParams — the single source of truth for the sim's free parameters.
 * fitSim / the ranking call this instead of hardcoding give/spill, so a re-run
 * of calibrate.mjs propagates automatically.
 */
export function getFusionParams(): FusionParams {
  return { ...FUSION_PARAMS }
}

/**
 * give(stretch) — the calibrated forgiveness band in mm for a cup of the given
 * fabric stretch (0 = rigid, 1 = very stretchy). This is the exact quantity
 * fitSim.ts computes inline as `2 + stretch*12`; consume this instead so the
 * tolerance stays calibrated in one place.
 */
export function give(stretch: number): number {
  return FUSION_PARAMS.give0 + stretch * FUSION_PARAMS.givePerStretch
}

/** How well the current calibration fits reality — for surfacing in the UI/docs. */
export function getFusionFit(): FusionFit {
  const c = calibration as {
    recommended?: { agreement?: number; corr?: number; fit?: number; communityCorr?: number | null }
    realSignal?: { transitionsUsed?: number }
  }
  return {
    agreement: c.recommended?.agreement ?? 0,
    spillJumpCorr: c.recommended?.corr ?? 0,
    fit: c.recommended?.fit ?? 0,
    transitionsUsed: c.realSignal?.transitionsUsed ?? 0,
    communityCorr: c.recommended?.communityCorr ?? null,
  }
}

/** Provenance string for the calibration, for an honest "how we know" footnote. */
export const FUSION_SOURCE =
  'Calibrated against data/size-transitions.json via scripts/fusion/calibrate.mjs. Physics bootstraps where data is thin; real outcomes correct the physics.'
